// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function CreateUser(arg1:string):Promise<Record<string, any>>;

export function DeleteUser(arg1:string):Promise<void>;

export function GetAuthStatus():Promise<Record<string, any>>;

export function GetChannels():Promise<Array<string>>;

export function GetConfigPath():Promise<string>;

export function GetGUIConfigPath():Promise<string>;

export function GetHealth():Promise<Record<string, any>>;

export function GetLLMConfig():Promise<main.LLMConfigSpec>;

export function GetLogs(arg1:number):Promise<Array<string>>;

export function GetMetrics():Promise<Record<string, any>>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetUptime():Promise<number>;

export function IsRunning():Promise<boolean>;

export function ListUsers():Promise<Array<Record<string, any>>>;

export function LoadConfig():Promise<config.Config>;

export function Logout():Promise<void>;

export function RequestDesktopLoginCode(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RestartServer():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartServer():Promise<void>;

export function StopServer():Promise<void>;

export function VerifyDesktopLoginCode(arg1:string,arg2:string,arg3:string):Promise<void>;
