// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUser(arg1) {
  return window['go']['main']['App']['CreateUser'](arg1);
}

export function DeleteUser(arg1) {
  return window['go']['main']['App']['DeleteUser'](arg1);
}

export function GetAuthStatus() {
  return window['go']['main']['App']['GetAuthStatus']();
}

export function GetChannels() {
  return window['go']['main']['App']['GetChannels']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetGUIConfigPath() {
  return window['go']['main']['App']['GetGUIConfigPath']();
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetLLMConfig() {
  return window['go']['main']['App']['GetLLMConfig']();
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMetrics() {
  return window['go']['main']['App']['GetMetrics']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetUptime() {
  return window['go']['main']['App']['GetUptime']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function ListUsers() {
  return window['go']['main']['App']['ListUsers']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RequestDesktopLoginCode(arg1, arg2) {
  return window['go']['main']['App']['RequestDesktopLoginCode'](arg1, arg2);
}

export function RestartServer() {
  return window['go']['main']['App']['RestartServer']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartServer() {
  return window['go']['main']['App']['StartServer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}

export function VerifyDesktopLoginCode(arg1, arg2, arg3) {
  return window['go']['main']['App']['VerifyDesktopLoginCode'](arg1, arg2, arg3);
}
